### ISSUE TITLE
[Bug]: Dockerfile doesn't run because entrypoint.sh is missing executable mod

### ISSUE THREAD

**Issue by jaymgonzalez** [Sygil-Dev/sygil-webui#1479]
### What happened?

`sd/entrypoint.sh: Permission denied` error message when trying to build the image.

### Version

0.0.1 (Default)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jaymgonzalez** [comment]
Hi! I'm trying to push the fix but is not letting me

`Please make sure you have the correct access rights
and the repository exists.`

Probably I need some credentials to push to dev branch?

Thanks

**Comment by codefaux** [comment]
You can't push to someone else's repo.

Fork this repo, clone your fork, fix it on your end, and commit in your local branch.

Issue a Pull Request using the GitHub webpage for your branch after making relevant commits; a new button appears to assist with Pull Requests.
