### ISSUE TITLE
[Bug]:  ModuleNotFoundError: No module named 'jsonmerge' on m1

### ISSUE THREAD

**Issue by yzyjsjem** [Sygil-Dev/sygil-webui#1518]
### What happened?

I find another report has the same issue but it was closed. I find several solutions to solve it but all failed, even though some have been proved to be useful on windows. But they don't work on mac. I tried to install jsonmerge from almost everywhere but it still can't be found. Can some mac users give me some advice?

### Version

0.0.1 (Default)

### Where are you running the webui?

MacOS

### Relevant log output

```shell
Traceback (most recent call last):
  File "/Users/yangzhenyu/Documents/stable-diffusion-webui/webui.py", line 12, in <module>
    from modules import devices, sd_samplers
  File "/Users/yangzhenyu/Documents/stable-diffusion-webui/modules/sd_samplers.py", line 7, in <module>
    import k_diffusion.sampling
  File "/Users/yangzhenyu/Documents/stable-diffusion-webui/repositories/k-diffusion/k_diffusion/__init__.py", line 1, in <module>
    from . import augmentation, config, evaluation, external, gns, layers, models, sampling, utils
  File "/Users/yangzhenyu/Documents/stable-diffusion-webui/repositories/k-diffusion/k_diffusion/config.py", line 6, in <module>
    from jsonmerge import merge
ModuleNotFoundError: No module named 'jsonmerge'
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by creaoy** [comment]
Having the same issue on Mac M1:

`Traceback (most recent call last):
  File "/Users/creaoy/Documents/code/stable-diffusion-webui/webui.py", line 12, in <module>
    from modules import devices, sd_samplers
  File "/Users/creaoy/Documents/code/stable-diffusion-webui/modules/sd_samplers.py", line 7, in <module>
    import k_diffusion.sampling
  File "/Users/creaoy/Documents/code/stable-diffusion-webui/repositories/k-diffusion/k_diffusion/__init__.py", line 1, in <module>
    from . import augmentation, config, evaluation, external, gns, layers, models, sampling, utils
  File "/Users/creaoy/Documents/code/stable-diffusion-webui/repositories/k-diffusion/k_diffusion/config.py", line 6, in <module>
    from jsonmerge import merge
ModuleNotFoundError: No module named 'jsonmerge'`

**Comment by 2refocus** [comment]
Same here
`Traceback (most recent call last):
  File "/Users/akaempf/Documents/stable-diffusion-webui/webui.py", line 12, in <module>
    from modules import devices, sd_samplers
  File "/Users/akaempf/Documents/stable-diffusion-webui/modules/sd_samplers.py", line 7, in <module>
    import k_diffusion.sampling
  File "/Users/akaempf/Documents/stable-diffusion-webui/repositories/k-diffusion/k_diffusion/__init__.py", line 1, in <module>
    from . import augmentation, config, evaluation, external, gns, layers, models, sampling, utils
  File "/Users/akaempf/Documents/stable-diffusion-webui/repositories/k-diffusion/k_diffusion/config.py", line 6, in <module>
    from jsonmerge import merge
ModuleNotFoundError: No module named 'jsonmerge'`

**Comment by BigZampano** [comment]
Same here... glad I found this thread, hope there is a fix...

**Comment by theskyisthelimit** [comment]
same here

`from jsonmerge import merge
ModuleNotFoundError: No module named 'jsonmerge'`

**Comment by TeaJea** [comment]
same, I note that there is only jsonmerge-1.8.0.dist-info but no jsonmerge in the Python\Lib\site-packages

**Comment by LandonReillyTroy** [comment]
same here ```
diffusion/config.py", line 6, in <module>
    from jsonmerge import merge
ModuleNotFoundError: No module named 'jsonmerge'
```

**Comment by ArielBenichou** [comment]
Same here, I've installed the `jsonmerge` with the `conda install -c defusco jsonmerge` command.
but after that I got another error of another dependency missing:
```
ModuleNotFoundError: No module named 'einops'
```
I guess there is a problem with installing the python dependencies.

**Comment by BrassHead** [comment]
Installing jsonmerge just lead to getting more module not found errors.

I noticed that the onnx package had trouble installing because it could not find cmake (this error was much earlier in the output from setup_mac.sh). Homebrew puts cmake in /opt/homebrew/bin/ . The fix for me was to add a link in a more standard place with

`sudo ln -s /opt/homebrew/bin/cmake /usr/local/bin/cmake`

and then restart terminal. After that setup_mac.sh ran to completion and the web_ui server started.

**Comment by 2refocus** [comment]
> Installing jsonmerge just lead to getting more module not found errors.
> 
> I noticed that the onnx package had trouble installing because it could not find cmake (this error was much earlier in the output from setup_mac.sh). Homebrew puts cmake in /opt/homebrew/bin/ . The fix for me was to add a link in a more standard place with
> 
> `sudo ln -s /opt/homebrew/bin/cmake /usr/local/bin/cmake`
> 
> and then restart terminal. After that setup_mac.sh ran to completion and the web_ui server started.

i tried your solution but didn't work for me. I realized that i have this structure:
`/opt/homebrew/bin/ccmake`  so I deleted the /usr/local/bin/cmake and tried it again with `sudo ln -s /opt/homebrew/bin/ccmake /usr/local/bin/cmake` and run the setup_mac.sh again but with no luck.

**Comment by ArielBenichou** [comment]
@BrassHead
> The fix for me was to add a link in a more standard place with
> 
> `sudo ln -s /opt/homebrew/bin/cmake /usr/local/bin/cmake`
> 
> and then restart terminal. After that setup_mac.sh ran to completion and the web_ui server started.
 
I created the link with `sudo ln -s /opt/homebrew/bin/cmake /usr/local/bin/cmake` but this didn't help I still get this:
```sh
Traceback (most recent call last):
  File "/Users/arielbenichou/Documents/stable-diffusion-webui/webui.py", line 12, in <module>
    from modules import devices, sd_samplers
  File "/Users/arielbenichou/Documents/stable-diffusion-webui/modules/sd_samplers.py", line 7, in <module>
    import k_diffusion.sampling
  File "/Users/arielbenichou/Documents/stable-diffusion-webui/repositories/k-diffusion/k_diffusion/__init__.py", line 1, in <module>
    from . import augmentation, config, evaluation, external, gns, layers, models, sampling, utils
  File "/Users/arielbenichou/Documents/stable-diffusion-webui/repositories/k-diffusion/k_diffusion/config.py", line 6, in <module>
    from jsonmerge import merge
ModuleNotFoundError: No module named 'jsonmerge'
```

**Comment by lustfeind** [comment]
I got it running installing the missing dependencies. And there are a lot! This install script lacks them. 

bash -l -c "conda activate web-ui; pip install jsonmerge einops clean-fid resize_right torchdiffeq lark gradio fastapi omegaconf piexif fonts font-roboto pytorch_lightning transformers kornia realesrgan scunet timm"

**Comment by BigZampano** [comment]
> I got it running installing the missing dependencies. And there are a lot! This install script lacks them.
> 
> bash -l -c "conda activate web-ui; pip install jsonmerge einops clean-fid resize_right torchdiffeq lark gradio fastapi omegaconf piexif fonts font-roboto pytorch_lightning transformers kornia realesrgan scunet timm"

You are a true hero, that worked...!
Yesterday I also tried to install the missing pieces, but I gave up after 5 or 6... lol...
Thank you very much for the install code snippet..!

**Comment by jet3004** [comment]
> I got it running installing the missing dependencies. And there are a lot! This install script lacks them.
> 
> bash -l -c "conda activate web-ui; pip install jsonmerge einops clean-fid resize_right torchdiffeq lark gradio fastapi omegaconf piexif fonts font-roboto pytorch_lightning transformers kornia realesrgan scunet timm"

Searched high and low for _THIS ANSWER RIGHT HERE_. Solved everything, bravo.

**Comment by Kawaa-qwq** [comment]
> I got it running installing the missing dependencies. And there are a lot! This install script lacks them.
> 
> bash -l -c "conda activate web-ui; pip install jsonmerge einops clean-fid resize_right torchdiffeq lark gradio fastapi omegaconf piexif fonts font-roboto pytorch_lightning transformers kornia realesrgan scunet timm"

you are the real hero! I fix it
