### ISSUE TITLE
[Idea]: Give more information than just "403" when downloading the SD model

### ISSUE THREAD

**Issue by RaymondTracer** [Sygil-Dev/sygil-webui#1571]
### What happened?

I had to figure out myself how to download the model, it would've helped if you just put the instructions up when downloading it instead of showing a generic 403 error.

### Version

0.0.1 (Default)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sugarb1tch** [comment]
im having trouble installing myself- could you let me know how you did it? thanks.

**Comment by ZeroCool940711** [comment]
This has been improved on the dev branch, will be on master on the next merge we do.
