### ISSUE TITLE
[Bug]: wiki link is broken

### ISSUE THREAD

**Issue by sonar0m** [Sygil-Dev/sygil-webui#1586]
### What happened?

when any wiki link you get for https://sygil-dev.github.io/stable-diffusion-webui/ you get a 404

### Version

0.0.1 (Default)

### What browsers are you seeing the problem on?

Firefox

### Where are you running the webui?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by codedealer** [comment]
Links are updated to the new web address
