### ISSUE TITLE
[Bug]: discord role-requests system not working

### ISSUE THREAD

**Issue by camenduru** [Sygil-Dev/sygil-webui#1593]
### What happened?

![Screenshot 2022-10-26 051635](https://user-images.githubusercontent.com/54370274/197918899-a7d71d79-4b22-41fc-837c-e581aba91885.jpg)

### Version

0.0.1 (Default)

### What browsers are you seeing the problem on?

Chrome

### Where are you running the webui?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Kasiya13** [comment]
The bot is down atm, thanks for letting us know. I'll give you a use role manually but please try to come back to it later and grab the rest.
