### ISSUE TITLE
I entered my hugginface token but : 401 client error unauthorized for url: https://huggingface.co/...

### ISSUE THREAD

**Issue by DiegoRRR** [Sygil-Dev/sygil-webui#1623]
Hello

In "Models Manager" when trying to download "Stable Diffusion v1.5" and "Latent Diffusion Super Resolution (LDSR)" I get error messages.
In cmd :

`401 Client Error: Unauthorized for url: https://huggingface.co/...`

or

`403 Client Error: Forbidden for url: https://huggingface.co/...`

and in the page :
```
Bad message format
'setIn' cannot be called on an ElementNode
```
I did create a hugginface token and entered it in the settings panel though.

Please someone help on this.
Thanks.

**Comment by seanwcom** [comment]
You need to go here and accept the license agreement, then the download button should work: https://huggingface.co/runwayml/stable-diffusion-v1-5

**Comment by DiegoRRR** [comment]
Thanks. :)
