### ISSUE TITLE
Some questions about new webui Streamlit 

### ISSUE THREAD

**Issue by nixodmin** [Sygil-Dev/sygil-webui#1624]
Good day! 

Today webui on my Windows PC was updated, but after than It runs Streamlit with lots of errors.
Even I have to delete all that was installed, clear anaconda env and install all again (modules download in webui - this is real great!, even got my token from Hugginface to download Stable Diffusion v1.5)

But.

1) I cant find in Streamlit interface where to upscale images (modules were loaded - LDSR and RealESRGAN)

2) got warning "anaconda3\envs\ldm\lib\site-packages\torch\distributed\distributed_c10d.py:181: UserWarning: torch.distributed.reduce_op is deprecated, please use torch.distributed.ReduceOp instead"

3) every first start image generation unsuccesfull with error "ERROR      | 2022-10-30 11:22:10 | sd_utils:load_models:471 - 'LatentDiffusion' object has no attribute 'args'" but after this error images generates normal without issues

2 and 3 not such critical errors, but where I can upscale images )

**Comment by ZeroCool940711** [comment]
@nixodmin the warning you get on 2 is normal and there is nothing I can do to remove it for now, you can just ignore it as it wont stop you from using the UI, the issue on number 3 is part of a leftover code from a previous implementation we tried to do of some options that later got added to diffusers directly, I will remove that code to fix this issue but that should also not stop you from using the UI normally, as for number 1 they are under the Advanced expander on the right side of each tab, there is a section called Post Processing where both upscaling and face restoration are.
btw, join our discord, we can help there with any issue you have as we are always active there, you can also just mention me at any time if you need help with something.

**Comment by nixodmin** [comment]
@ZeroCool940711 thanx for answer!

But upscaler missing :(

In Advanced expander -> Post Processing tab I have only Face Restoration "Use GFPGAN" no Upscale (browser Firefox, Chrome)

In Settings -> General I have options for choose Upscaler type (change between LDSR and RealESRGAN not changes situation), and options for RealESRGAN model

In Settings -> Image Processing there is only "Default Img2Txt Batch Size" option for GFPGAN

In Model Manger RealESRGAN and LDSR installed with green checkbox (all of them installed trough webui)

Strange, but in console no errors matching with RealESRGAN or LDSR. 

I have clear installation:
- conda version 22.9.0
- env (ldm) was cleared
- sygil-webui was installed (using git) in new empty folder
- all models were installed through webui (downloaded in console)
- even z_version_env.tmp were once deleted





![no_upscale](https://user-images.githubusercontent.com/116359084/198864496-67d32f68-2bc5-4442-ae64-ba25e8941643.jpg)
![no_upscale2](https://user-images.githubusercontent.com/116359084/198864510-5d93ce71-b8fa-41ab-accd-d80a0cb552d4.jpg)
![no_upscale3](https://user-images.githubusercontent.com/116359084/198864552-cb173fdc-acb4-4b98-a26f-2dc4322a869b.jpg)

**Comment by ZeroCool940711** [comment]
First of all, I see the layout is messed up, this is an issue we have with streamlit and the CSS on the page so, when you see that happen please refresh the page a few times until it goes away so the layout comes back to normal, this will make things easier for you as some expanders and other options get moved out of place when this sometimes happens, it is a random thing with streamlit and not a lot we can do to fix it, just a thing we have to deal with. Once the layout is back to normal make sure you share the screenshot of the Post Processing tab correctly as I can't see the options from there on your screenshots, the upscaling tab wont show anything if the realesrgan model is not downloaded properly so, maybe it was that something went wrong during the install, you can try to remove the `models/realesrgan` folder and try again to download it from the model manager, also, make sure that if you want to use upscaling the `Use Upscaling` checkbox is enabled as even if you change the model for upscaling without enabling that option it won't be used at all, GFPGAN is enabled by default but you can also disable it if you want, for the settings page only the GFPGAN section is implemented and there is just one option which you can just ignore.

**Comment by nixodmin** [comment]
Solved! Thanx a lot!

Magic word "CSS" make me open code of page in browser and I find the root of my problem! 

I use 4K TV for my PC, so Windows upscale fonts to 300% almost everythere

I make less upscale in browser and tab "Upscaling" appeared near 'Face Restoration'

Sorry, for such a waste of your time! But maybe my issue helps some other people )



![no_upscale5](https://user-images.githubusercontent.com/116359084/198865073-0ef21d77-4d7f-4bc4-b94c-e4d3a1a3e5f8.jpg)

**Comment by ZeroCool940711** [comment]
@nixodmin dont worry, its okay, the layout is messed up not because of your resolution but more because of the UI itself, let me explain a bit in case you are interested. The issue we have is that streamlit doesn't have fixed classes or ids for the page elements or a way for us to set them, so, when we want to modify the css to do something like what I do with the text area for the prompt which I make smaller to fit the height of the generate button give it or take a few pixels then things become complicated as the ids and classes can change sometimes depending on streamlit's mood xD, this end up messing things sometimes and the layout not working properly, the text area you see there is not supposed to be that size by default, it should be smaller, you can still drag it and resize it to fit your text if you need it to be larger tho, the expanders are also not supposed to be on top of other stuff on the UI, all that is caused because streamlit doesnt allow us to set our own ids for elements or things so we have to hack around the css and when things change randomly then it gets messed up like that.

**Comment by nixodmin** [comment]
Got it! Thanx once more!
