### ISSUE TITLE
[Bug]: Websockets code crashes on colab

### ISSUE THREAD

**Issue by kholbekj** [Sygil-Dev/sygil-webui#1636]
### What happened?

When I follow the flow in the notebook in colab, I can access the webinterface, but it has basically no controls (except for the menu and text input), and the log from the server is crashy looping.

This happens over and over.

### Version

0.0.1 (Default)

### What browsers are you seeing the problem on?

Chrome

### Where are you running the webui?

Colab

### Relevant log output

```shell
2022-11-02 17:39:35.106 Task exception was never retrieved
future: <Task finished name='Task-797' coro=<WebSocketProtocol13.write_message.<locals>.wrapper() done, defined at /usr/local/lib/python3.10/site-packages/tornado/websocket.py:1090> exception=WebSocketClosedError()>
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/tornado/websocket.py", line 1092, in wrapper
    await fut
tornado.iostream.StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/tornado/websocket.py", line 1094, in wrapper
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ZeroCool940711** [comment]
@kholbekj that happens even locally when you just refresh the page too fast or rerun too fast, it usually is not a critical crash and you can just continue to use the UI as normal or refresh the page and things go back to normal.

**Comment by kholbekj** [comment]
Maybe the log is unrelated to the issue then, the UI stops loading after
the text input, no submit, other tabs have no content.

On November 2, 2022, Linda_pp ***@***.***> wrote:
> @kholbekj <https://github.com/kholbekj> that happens even locally when
> you just refresh the page too fast or rerun too fast, it usually is
> not a critical crash and you can just continue to use the UI as normal
> or refresh the page and things go back to normal.
>

—
Reply to this email directly, view it on GitHub
<https://github.com/Sygil-Dev/sygil-webui/issues/1636#issuecomment-
1301056825>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/AAVIKCZNVCWUB7OXVCJLOCDWGKXVTANCNFSM6AAAAAARVLBF24>.
You are receiving this because you were mentioned.Message ID: <Sygil-
***@***.***>

**Comment by ZeroCool940711** [comment]
That's probably another issue, either the models are missing or some other element on the UI crashed, streamlit just stops the code execution where the error happens so anything that is created after that part just do not show up on the UI which usually make the submit form not have a button or some element being missing, if you are on the dev branch try to check the logs folder, there should be some logs files with info on the crash, also, check the console a bit higher as usually the last part of the console just shows something unrelated to the original error.

**Comment by kholbekj** [comment]
Hah, I booted it up again to get a better log, but this time I took it real chill before opening the first time, and it worked.

Thanks!
