### ISSUE TITLE
cannot import name 'no_rerun' from 'streamlit_server_state'

### ISSUE THREAD

**Issue by DiegoRRR** [Sygil-Dev/sygil-webui#1713]
I let it update and now I have this issue :

```
ImportError: cannot import name 'no_rerun' from 'streamlit_server_state' (C:\Users\Gros2\miniconda3\envs\ldm\lib\site-packages\streamlit_server_state\__init__.py)
Traceback:

File "C:\Users\Gros2\miniconda3\envs\ldm\lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 562, in _run_script
    exec(code, module.__dict__)
File "C:\Users\Gros2\stable-diffusion-webui__sygil\scripts\webui_streamlit.py", line 22, in <module>
    from sd_utils import st, hc, load_configs, load_css, set_logger_verbosity,\
File "scripts\sd_utils\__init__.py", line 25, in <module>
    from streamlit_server_state import server_state, server_state_lock, no_rerun
```

Can anybody help please ?

**Comment by ZeroCool940711** [comment]
Make sure the streamlit-server-state library is the latest version, you can either install it manually or you can run the `webui.bat` or `webui.sh` a couple of times depending on your platform, it will install all dependencies automatically, for some reason conda doesn't install some dependencies the first time the webui runs and you need to run it a couple of times for it to work.

**Comment by DiegoRRR** [comment]
I ran webui.bat several times, deleted z_version_env.tmp to force it to check the files, but the problem still happens.
How to install it manually ?

**Comment by ZeroCool940711** [comment]
mmm, in that you might need to do a few things, we will need to figure out some stuff on your installation and from where things are running, to make things faster I think it would be better if you [join our discord server](https://discord.gg/ttM8Tm6wge) and ask about this issue on the `streamlit-webui` channel, I will help you with it there as it will be faster to have a conversation there than doing so here on github. If you dont want to join the discord server then just let me know and we can continue the conversation here, will be slower but still doable.

**Comment by DiegoRRR** [comment]
I kept on trying and it seems to have finally fixed it by itself.

**Comment by ZeroCool940711** [comment]
@DiegoRRR good to know you managed to fix it, if you have any other issue don't hesitate to ask on our discord or open an issue here.
