### ISSUE TITLE
hlky/sd-webui docker is outdated

### ISSUE THREAD

**Issue by ButterMeWaffle** [Sygil-Dev/sygil-webui#1762]
Is it possible to have the docker image (https://hub.docker.com/r/hlky/sd-webui) updated to the newest version? 

its missing quite a few quality of life features

**Comment by ZeroCool940711** [comment]
@ButterMeWaffle hlky is no longer part of our organization, if someone can help me with a PR to fix the docker image which I think need some fixing we can probably move things to my own account or someone else's, if you or anyone wants to maintain it that would be even better as I pretty much don't use docker myself so I won't be able to test stuff and make sure it's always up-to-date.

**Comment by ButterMeWaffle** [comment]
@ZeroCool940711 

I dont use docker either, outside of my unraid box. If I get some extra time this weekend I can try to figure it out and get the image updated but I would be going in mostly blind.

**Comment by ButterMeWaffle** [comment]
does anyone have the docker-compose file? I have no idea what it should look like.

even better if you have the code used in https://hub.docker.com/r/hlky/sd-webui

**Comment by ZeroCool940711** [comment]
@ButterMeWaffle we have these ([1](https://github.com/Sygil-Dev/sygil-webui/blob/master/Dockerfile), [2](https://github.com/Sygil-Dev/sygil-webui/blob/master/Dockerfile_base), [3](https://github.com/Sygil-Dev/sygil-webui/blob/master/Dockerfile_runpod)) on the repo, I think those are the ones used to build the different docker images including the one on runpod.

**Comment by ButterMeWaffle** [comment]
@ZeroCool940711 unfortunately those aren't what im in need of. I did some digging and found [this](https://github.com/Seacant/stable-diffusion-webui/blob/c6baf15b9ac643966df9cf6261f10cc92c266ae9/docker-compose.yml) and it looks a lot like what I need but I wish I could get the version hkly used.

**Comment by ZeroCool940711** [comment]
I think you should join our discord server and try asking there, maybe someone can help us figure things out, I remember one or two people mentioning docker before and wanting to fix things for that.

**Comment by ButterMeWaffle** [comment]
ill do that

**Comment by michaelzern** [comment]
You'll have to clone the repo, then run\
`docker login` \
`docker build -t . sd-webui` \
`docker tag sd-webui USERNAME/sd-webui:latest` \
`docker push USERNAME/sd-webui:latest` \
Send this up to your dockerhub account. That should push out the latest image, just make sure any changes that need made for the [Dockerfile](https://github.com/Sygil-Dev/sygil-webui/blob/master/Dockerfile) are present.\
As for unraid you can upload it yourself, or have original person upload the updated XML pointing to the new repo.\
Hopefully this helps.

**Comment by ButterMeWaffle** [comment]
I have a build up on buttermewaffle/sygil-webui:latest 

it isnt completed enough for a PR or to go up on community apps just yet but I will get that done when I have some time. for now the build I have up works

**Comment by ButterMeWaffle** [comment]
sorry I was away for the weekend, hoping to have the PR together this week.

**Comment by michaelzern** [comment]
ZeroCool has a repo up at [tukirito/sygil-webui](https://hub.docker.com/r/tukirito/sygil-webui). I sent more info through the discord.

**Comment by michaelzern** [comment]
I set my own up as well for testing. However, for the long-term health of this project, I recommend using the lead developer's Docker repo to ensure better alignment and support going forward.

**Comment by ButterMeWaffle** [comment]
I might need to be the owner of the repo if im going to get it approved in unraids community apps.

**Comment by ZeroCool940711** [comment]
You can have your own docker hub repos if you want or if you need it, you can also fork our repo and modify the dockerfile if you need to, the Dockerfile and the repo we set up on my account ([tukirito/sygil-webui](https://hub.docker.com/r/tukirito/sygil-webui)) is so others can use it as a base image or for reference if they need it and so we have an official docker image that we can update easily for the long-term health of the project as @michaelzern said, previously, it was on hlky's account and he is no longer part of the organization or project so it's better to have something we can modify when needed, @michaelzern tried to figure out how to make it so we could update the image on docker hub automatically when commits hit the master branch here but the GitHub action wasn't working properly so for now we have to update the docker image manually but still, It's something we can update and its no longer behind the master branch or at least not as much as the previous one was as it had not been updated for months. If anyone wants to help to figure out how to make a Github action that we can use to update the docker image automatically and make it work properly then we can use that but for now even having the image updated manually is better than nothing at all.

**Comment by ButterMeWaffle** [comment]
@ZeroCool940711 iirc you need to pay for docker-hub to have this feature

**Comment by ButterMeWaffle** [comment]
sorry ive been swamped and haven't been able to get the code cleaned up and pushed, ill try to get it out there ASAP

**Comment by ButterMeWaffle** [comment]
guess someone beat me to it -> https://hub.docker.com/r/tukirito/sygil-webui

its for the best, I was cleaning out my drives and accidentally removed all of my changes

**Comment by Joly0** [comment]
> guess someone beat me to it -> https://hub.docker.com/r/tukirito/sygil-webui
> 
> its for the best, I was cleaning out my drives and accidentally removed all of my changes

Hey, i am curious now. Would you suggest using your docker image or tukirito´s?

**Comment by ButterMeWaffle** [comment]
> > guess someone beat me to it -> https://hub.docker.com/r/tukirito/sygil-webui
> > its for the best, I was cleaning out my drives and accidentally removed all of my changes
> 
> Hey, i am curious now. Would you suggest using your docker image or tukirito´s?

Sorry for the delay, I would recommend to use the version found in community apps (tukiritos I believe). it appears to run great and will hopefully be kept up to date but I cant speak to that
