### ISSUE TITLE
[Bug]: Outputs are only gray textured images when adding a textual inversion prompt

### ISSUE THREAD

**Issue by jrusovick** [Sygil-Dev/sygil-webui#1790]
### What happened?

When I am not including a textual conversion in the prompt, the outputs generate as I would expect.

However, replicating the prompt for the exact same prompt then adding a textual inversion to the txt2img prompt, a gray texture is the only output I receive - no matter what model, textual inversion prompt, syntax, positive prompt, negative prompt, etc.

**Expected to Happen:** Prompt generates any output other than a texture.

Here is a screenshot, just after I generated one image (without embedding a textual inversion prompt):

![without_textualinversion](https://github.com/Sygil-Dev/sygil-webui/assets/15897375/e118d75c-2673-4145-ab3a-cd97f00c5ea8)

And here is just following the generation of one image (with an embedded textual inversion prompt):

![with_textualinversion](https://github.com/Sygil-Dev/sygil-webui/assets/15897375/cbdf3f31-6907-415f-b84c-598ffd7f0000)

As you can see its just a grayish texture, and that is what happens for every output with a textual inversion added. This occurs seemingly no matter what prompts I change, the models I try, LORAs are working properly - it is only the textual inversion.

Hope you can help, and thanks in advance!

### Version

0.0.1 (Default)

### What browsers are you seeing the problem on?

Chrome

### Where are you running the webui?

Windows

### Custom settings

```shell
No custom settings.
```

### Relevant log output

```shell
No log output.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ZeroCool940711** [comment]
That doesn't look like our UI, at least not the Streamlit UI which is the recommended one to use. If you are using the gradio UI from our repo please switch to the streamlit version and make sure you are on the latest code from the repo.

**Comment by jrusovick** [comment]
I have an AMD GPU - 6700 xt - so I need to use the DirectML version. 

Would that have an impact?
