### ISSUE TITLE
[Bug]: All was well until it auto updated (cannot import name 'hc' from 'sd_utils')

### ISSUE THREAD

**Issue by eagleEggs** [Sygil-Dev/sygil-webui#1813]
### What happened?

Last week all was well, and now this error on launch (Windows 10):

File "C:\Users\eagle\miniconda3\envs\ldm\lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 563, in _run_script
    exec(code, module.__dict__)
File "C:\Users\eagle\sygil-webui\scripts\webui_streamlit.py", line 22, in <module>
    from sd_utils import (

ImportError: cannot import name 'hc' from 'sd_utils' (scripts\sd_utils\__init__.py)

**Besides that... Is there a way to easily disable auto updates?**

Ty.

### Version

0.0.1 (Default)

### What browsers are you seeing the problem on?

Firefox

### Where are you running the webui?

Windows

### Custom settings

```shell
None
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by Readerlution** [comment]
same issue. seems like the entire 'hc' related code got deleted from st_utils

**Comment by ZeroCool940711** [comment]
I think I figured out what happened, it seems to be an issue with `pre-commit`, for some reason it removes the imports for hydralit and hydralit_components every single time I commit to the repo, so, the fix I did before to address the import issue was completely reverted, same with other stuff, I will go thru the whole commit history and see what else it messed up. Give me a couple hours to figure out what else broke and then I will push a fix to the repo and the master branch.

**Comment by ZeroCool940711** [comment]
@eagleEggs @Readerlution I just pushed a fix and merged to master so the next time you run the UI it should auto update, let me know if it fixed the issue, if it didn't let me know as well so I can continue to look for what else might have broken because of pre-commit, I already removed pre-commit as it was breaking more stuff than it was fixing so we shouldn't have the same problem again with it.

**Comment by ZeroCool940711** [comment]
I assume things are working properly now so I will be closing this issue then.
